### ISSUE TITLE
feat: skip process of making FGB if uploaded file format is already in FGB

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub-data-pipeline#29]
After merging this PR https://github.com/UNDP-Data/geohub/pull/1945 to GeoHub, now users can upload FlatGeobuf format. The data pipeline should skip the process of converting to FGB and immediately use tippecanoe to start making PMTiles. So it can save some time to process it.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1221236706) by [Unito](https://www.unito.io)

**Comment by iferencik** [comment]
This is not advisable. tippecanoe can consume FGB directly but it has to be in 4326 Latlon WGS84. If it is not the pmtiles will be weird and unusable
